apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: wp-ns
  labels:
    app: adminer
spec:
  ports:
  - name: adminer
    port: 8000 # has to match kubectl port-forward
    targetPort: 8080 # has to match deployment.spec.template.spec.containers.ports.containerPort
  type: ClusterIP
  selector:
    app: adminer