apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: wp-ns
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer # has to match .spec.template.metadata.lables
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adminer # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080 # has to match service.spec.ports.targetPort
          envFrom:
            - secretRef:
                name: wordpress
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
