apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: wp-ns
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress # has to match .spec.template.metadata.lables
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wordpress # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: domainname-wp-pod
          image: wordpress
          ports:
            - containerPort: 80 # has to match service.spec.ports.targetPort
          envFrom:
            - secretRef:
                name: wordpress
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /wp-login.php
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /wp-login.php
              port: https
              scheme: HTTPS
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 6
          volumeMounts:
            - name: pvcmount-wp # has to match .spec.template.spec.volumes.persistentVolumeClaim.claimName
              mountPath: /var/www/html
      volumes:
        - name: pvcmount-wp # has to match .spec.template.spec.containers.volumeMounts.name
          persistentVolumeClaim:
            claimName: domainname-wp-pvc
