apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: wordpress
    port: 80
    targetPort: 80
  type: ClusterIP
  selector:
    app: wordpress