apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp-ns
  labels:
    app: wordpress
spec:
  ports:
  - name: wordpress
    port: 80 # has to match kubectl port-forward
    targetPort: 80 # has to match deployment.spec.template.spec.containers.ports.containerPort
  type: ClusterIP
  selector:
    app: wordpress