apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - name: db
    port: 3306
  type: ClusterIP
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  serviceName: mariadb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady  
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - name: db
              containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb
            - configMapRef:
                name: mariadb
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          limits:
            storage: 1000Mi
          requests:
            storage: 500Mi
