apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: wp-ns
  labels:
    app: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306 # has to match statefulset.spec.template.spec.containers.ports.containerPort
  type: ClusterIP
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb # has to match .spec.template.metadata.labels
  serviceName: mariadb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady  
  template:
    metadata:
      labels:
        app: mariadb # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: domainname-db-pod
          image: mariadb
          ports:
            - name: mariadb
              containerPort: 3306 # has to match service.spec.ports.port
          envFrom:
            - secretRef:
                name: mariadb-db-secret
            - configMapRef:
                name: mariadb
          readinessProbe:
            exec:
              command: [mysqladmin, ping]
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: domainname-db-pvc # has to match .spec.volumeClaimTemplates.metadata.name
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: domainname-db-pvc # has to match .spec.template.spec.containers.volumeMounts.name
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          limits:
            storage: 1000Mi
          requests:
            storage: 500Mi
