apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: domainname-wp-pvc
  namespace: wp-ns
  labels:
    app: wordpress
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1000Mi
    requests:
      storage: 500Mi